[table]
title = "Skills"
columns = [
    { title = "ID", field = "id", width = 80 },
    { field = "name", span = 8 },
]
hidden_columns = ["created_at", "updated_at"]

[filter]

[editor]
enable = true
title_field = "name"
fields = [
    { title = "ID", field = "id", span = 8 },
    { field = "name", span = 8 },
]
hidden_columns = ["created_at", "updated_at"]

[create]
enable = false

[update]
enable = true
hidden_columns = ["created_at", "updated_at"]

[delete]
enable = true
